services:
  mongodb:
    image: mongo:latest
    container_name: fridaymongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: friday
      MONGO_INITDB_ROOT_PASSWORD: friday
    volumes:
      - ./fridaymongo:/data/db
