services:
  mongodb:
    image: mongo:latest
    container_name: parchamongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: parcha
      MONGO_INITDB_ROOT_PASSWORD: parcha
    volumes:
      - ./parchamongo:/data/db
