services:
  postgres:
    image: postgres:latest
    container_name: fridaypg
    ports:
      - 8734:5432
    environment:
      POSTGRES_USER: friday
      POSTGRES_PASSWORD: sexsux
      POSTGRES_DB: friday
    volumes:
      - ./fridaypg:/var/lib/postgresql/data
