// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.user */
export type UserId = string & { __brand: 'UserId' };

/** Represents the table public.user */
export default interface User {
  id: UserId;

  email: string;

  name: string | null;

  created_at: Date | null;

  google_id: string | null;

  picture: string | null;
}

/** Represents the initializer for the table public.user */
export interface UserInitializer {
  /** Default value: gen_random_uuid() */
  id?: UserId;

  email: string;

  name?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  google_id?: string | null;

  picture?: string | null;
}

/** Represents the mutator for the table public.user */
export interface UserMutator {
  id?: UserId;

  email?: string;

  name?: string | null;

  created_at?: Date | null;

  google_id?: string | null;

  picture?: string | null;
}
